### ISSUE TITLE
Incomplete code？

### ISSUE THREAD

**Issue by czy1999** [TmacMai/CoMPILE_Inductive_Knowledge_Graph#1]
where is collate_dgl2? Not found in this library or in Grail
```
File "train.py", line 9, in <module>
    from utils.graph_utils import collate_dgl, move_batch_to_device_dgl, collate_dgl2
ImportError: cannot import name 'collate_dgl2'
```

**Comment by TmacMai** [comment]
Sorry for the late reply. The files have been uploaded. Contact me if you have any further questions.

**Comment by TmacMai** [comment]
> where is collate_dgl2? Not found in this library or in Grail
> 
> ```
> File "train.py", line 9, in <module>
>     from utils.graph_utils import collate_dgl, move_batch_to_device_dgl, collate_dgl2
> ImportError: cannot import name 'collate_dgl2'
> ```
Sorry for the late reply. The files have been uploaded. Contact me if you have any further questions.

**Comment by czy1999** [comment]
Thanks😀
